### ISSUE TITLE
ubuntu 18.04安装完无法登录， 提示系统错误

### ISSUE THREAD

**Issue by dbskccc** [lxerxa/actionview#29]
apache 错误信息如下：
```
[Sun Oct 28 21:47:37.864419 2018] [php7:error] [pid 31302] [client 10.20.30.6:51220] PHP Fatal error:  Uncaught Error: Call to a member function send() on array in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:107\nStack trace:\n#0 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(84): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#1 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#2 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#3 {main}\n  thrown in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 107, referer: http://10.20.30.5/
```
[error.log](https://github.com/lxerxa/actionview/files/2522823/error.log)

**Comment by lxerxa** [comment]
可以试试 16.04。18.04 没试过。

**Comment by luochen52** [comment]
@lxerxa 我使用 16.04 出现一模一样的问题，跟依赖包的版本有关系么？

**Comment by luochen52** [comment]
@dbskccc 找到解决办法了吗？

**Comment by lxerxa99** [comment]
@luochen52 mongodb能连接成功吗？是否执行config.sh文件？

**Comment by dbskccc** [comment]
@luochen52 因为第一次尝试就不成功，已经放弃了，我只是用户不是开发人员，不知道如何解决
